name: variables
  hosts: localhost
  vars:
    Course: "Ansible"
    Class: "DevOps"
    Time: "07:30 AM"
  tasks:
  - name: print override information
    vars:
      Course: "TeraForm"
      Class: "Weekday Devops and Ansible"
      Time: "08:00 AM"
    ansible.builtin.debug:
      msg: "Hi, I am learing {{Course}} from Join {{Class}} at {{Time}}"

  - name: print information
    ansible.builtin.debug:
      msg: "Hi, I am learing {{Course}} from Join {{Class}} at {{Time}}"