- name: variables from files
  hosts:
    localhost
  vas_files:
   -vars.yaml
  tasks:
  - name: print override information
    ansible.builtin.debug:
      msg: "I am learing {{Course}} from Join {{Class}} at {{Time}}"