- name: Fileters default value
  hosts: localhost
  tasks:
  - name: print default values
    ansible.builtin.debug:
      msg: "Hello {{Course | default('Ansible') }}"
  - name: print default number
    ansible.builtin.debug:
      msg: "Hello {{Course | default(3000) }}"
  - name: print default specaial char
    ansible.builtin.debug:
      msg: "Love you {{Course | default(3000) }}!"

  - name: upper case
    vars:
      greetings: "Hello, Good Morning"
    ansible.builtin.debug:
      msg: "{{greetings | upper}}"


#default('Ansible')- use qotes 'Char' for string
#default(1000)- dont use qotes for numbers