- name: Fileters default value
  hosts: localhost
  tasks:
  - name: print default values
    ansible.builtin.debug:
      msg: "Hello {{Course | default('Ansible') }}"
  - name: print default number
    ansible.builtin.debug:
      msg: "Hello {{Course | default(3000) }}"
  - name: print default specaial char
    ansible.builtin.debug:
      msg: "Love you {{Course | default(3000) }}!"

  - name: upper case
    vars:
      greetings: "Hello, Good Morning"
    ansible.builtin.debug:
      msg: "{{greetings | upper}}"

- name: Filters default value Play-2
  hosts: localhost
  vars:
    call: "Hello to all"
  tasks:
  - name: upper play level
    ansible.builtin.debug:
      msg: "{{call | upper}}"

- name: Filters default value Play-3
  hosts: localhost
  vars:
    call: "Hello to all"
  tasks:
  - name: lower play level
    ansible.builtin.debug:
      msg: "{{call | lower}}"

- name: Remove duplicate- Play4
  hosts: localhost
  tasks:
  - name: remove duplicate
    vars:
      numbers: (1 2 2 3 3 3 4)
    ansible.builtin.debug:
      msg: "{{numbers | unique}}"

- name: Remove duplicate -Play5
  hosts: localhost
  tasks:
  - name: remove duplicate
    vars:
      numbers: [1, 2, 2, 3, 3, 3, 4.5]
    ansible.builtin.debug:
      msg: "{{numbers | unique}}"
  #- name: remove duplicate
   # vars:
     # numbers: [1 2 2 3 3 3 4.5] #will not workout should have , and square bracket
    #ansible.builtin.debug:
      #msg: "{{numbers | unique}}"

- name: min and max
  hosts: localhost
  vars:
    ages: [25, 35, 45, 100, 22]
  tasks:
  - name: sort ages
    ansible.builtin.debug:
      msg: "min age {{ages | min}}, max age {{ages | max}}"

- name: covert numbers
  hosts: localhost
  vars:
    my_dict: #this is called as a dictonary or map or key/value pairs
      Course: Ansible
      Trainer: Shiva
      Duration: 120hrs
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_dict}}"

  - name: after convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_dict | dict2items }}"

- name: convert items to dict
  hosts: localhost
  vars:
    my_items:
    - ['key': 'Course', 'value': 'Ansible']
    - {'key': 'Trainer', 'value': 'Shiva'}
    - {'key': 'Duration', 'value': '120hrs'}
  tasks:
  - name: after convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_items | items2dict }}"



#default('Ansible')- use qotes 'Char' for string
#default(1000)- dont use qotes for numbers