- name: Fileters default value
  hosts: localhost
  tasks:
  - name: print default values
    ansible.builtin.debug:
      msg: "Hello {{Course | default('Ansible') }}"


#default('Ansible')- use qotes 'Char' for string
#default(1000)- dont use qotes for numbers